// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetProcesses() {
  return window['go']['main']['App']['GetProcesses']();
}

export function RestartProcess(arg1) {
  return window['go']['main']['App']['RestartProcess'](arg1);
}

export function StartProcess(arg1) {
  return window['go']['main']['App']['StartProcess'](arg1);
}

export function StopProcess(arg1) {
  return window['go']['main']['App']['StopProcess'](arg1);
}
