// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {database} from '../models';
import {exceptions} from '../models';
import {main} from '../models';
import {metrics} from '../models';
import {config} from '../models';

export function AddProcess(arg1:Record<string, any>):Promise<void>;

export function CheckoutGitBranch(arg1:string):Promise<void>;

export function ClearExceptions():Promise<void>;

export function ClearLogs():Promise<void>;

export function ClearQueryStatistics():Promise<void>;

export function CommitChanges(arg1:models.GitCommitOptions):Promise<void>;

export function CompareQueryPlans(arg1:string,arg2:string):Promise<models.QueryComparison>;

export function ConfirmAndExecuteQuery(arg1:string,arg2:number,arg3:boolean):Promise<database.QueryResult>;

export function ConnectDatabase(arg1:Record<string, any>):Promise<void>;

export function ConnectSSH(arg1:string):Promise<string>;

export function CreateGitBranch(arg1:string,arg2:string):Promise<void>;

export function CreateSSHTunnel(arg1:string,arg2:models.SSHTunnel):Promise<void>;

export function DeleteGitBranch(arg1:string,arg2:boolean):Promise<void>;

export function DeleteSSHServer(arg1:string):Promise<void>;

export function DeleteSavedConnection(arg1:string):Promise<void>;

export function DeleteSavedQuery(arg1:string):Promise<void>;

export function DiscardChanges(arg1:string):Promise<void>;

export function DisconnectDatabase():Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function ExecuteDatabaseQuery(arg1:string,arg2:number):Promise<database.QueryResult>;

export function ExplainDatabaseQuery(arg1:string):Promise<database.ExplainResult>;

export function ExportSSHSession(arg1:string,arg2:string):Promise<string>;

export function GetAvailablePlugins():Promise<Array<Record<string, any>>>;

export function GetConflictFile(arg1:string):Promise<models.GitConflictFile>;

export function GetDatabaseHealth():Promise<database.DatabaseHealth>;

export function GetDatabaseStatus():Promise<database.DatabaseStatus>;

export function GetDatabaseTables():Promise<Array<database.TableInfo>>;

export function GetDebugConfiguration():Promise<Record<string, any>>;

export function GetExceptions():Promise<Array<exceptions.Exception>>;

export function GetFrameworkInfo():Promise<Record<string, any>>;

export function GetGitBlame(arg1:string):Promise<models.GitBlameFile>;

export function GetGitBranches():Promise<Array<models.GitBranch>>;

export function GetGitDiff(arg1:models.GitDiffOptions):Promise<Array<models.GitDiff>>;

export function GetGitLog(arg1:models.GitLogOptions):Promise<Array<models.GitCommit>>;

export function GetGitStatus():Promise<models.GitStatus>;

export function GetLogs(arg1:Record<string, any>):Promise<Array<main.LogEntry>>;

export function GetMetrics():Promise<metrics.Metrics>;

export function GetN1Warnings():Promise<Array<models.N1Warning>>;

export function GetProcess(arg1:string):Promise<main.ProcessInfo>;

export function GetProcesses():Promise<Array<main.ProcessInfo>>;

export function GetProjectInfo():Promise<Record<string, any>>;

export function GetQueryDistribution():Promise<models.QueryDistribution>;

export function GetQueryStatistics():Promise<Array<database.QueryStatistic>>;

export function GetRequestQueryGroups(arg1:number):Promise<Array<models.RequestQueryGroup>>;

export function GetSSHServers():Promise<Array<models.SSHServer>>;

export function GetSSHSessions():Promise<Array<models.SSHSession>>;

export function GetSavedConnections():Promise<Array<config.DatabaseConnection>>;

export function GetSavedQueries():Promise<Array<database.SavedQuery>>;

export function GetSmartRecommendations():Promise<Array<models.SmartRecommendation>>;

export function GetTableColumns(arg1:string):Promise<Array<database.ColumnInfo>>;

export function GetTestRunner():Promise<Record<string, any>>;

export function GetWorkerPoolStats():Promise<Record<string, any>>;

export function IgnoreException(arg1:string):Promise<void>;

export function IgnoreQueryPattern(arg1:string):Promise<void>;

export function IsGitRepository():Promise<boolean>;

export function IsRailsConsoleRunning():Promise<boolean>;

export function ParseLogWithPlugin(arg1:string):Promise<models.LogEntry>;

export function RemoveProcess(arg1:string):Promise<void>;

export function ResetMetrics():Promise<void>;

export function ResizePTY(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizeRailsConsole(arg1:number,arg2:number):Promise<void>;

export function ResizeSSH(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveConflict(arg1:string,arg2:string):Promise<void>;

export function ResolveException(arg1:string):Promise<void>;

export function RestartProcess(arg1:string):Promise<void>;

export function RevertFile(arg1:string):Promise<void>;

export function RevertFileToCommit(arg1:string,arg2:string):Promise<void>;

export function SaveDatabaseConnection(arg1:Record<string, any>):Promise<void>;

export function SaveDatabaseQuery(arg1:string,arg2:string):Promise<database.SavedQuery>;

export function SaveSSHServer(arg1:models.SSHServer):Promise<void>;

export function SelectProjectDirectory():Promise<string>;

export function SetProjectDirectory(arg1:string):Promise<void>;

export function StageFiles(arg1:Array<string>):Promise<void>;

export function StartAllProcesses():Promise<void>;

export function StartProcess(arg1:string):Promise<void>;

export function StartRailsConsole():Promise<void>;

export function StopAllProcesses():Promise<void>;

export function StopProcess(arg1:string):Promise<void>;

export function StopRailsConsole():Promise<void>;

export function UnstageFiles(arg1:Array<string>):Promise<void>;

export function WriteSSH(arg1:string,arg2:string):Promise<void>;

export function WriteToPTY(arg1:string,arg2:string):Promise<void>;

export function WriteToRailsConsole(arg1:string):Promise<void>;
