// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs():Promise<void>;

export function GetLogs(arg1:Record<string, any>):Promise<Array<Record<string, any>>>;

export function GetProcesses():Promise<Array<Record<string, any>>>;

export function RestartProcess(arg1:string):Promise<void>;

export function StartProcess(arg1:string):Promise<void>;

export function StopProcess(arg1:string):Promise<void>;
