// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {exceptions} from '../models';
import {main} from '../models';
import {metrics} from '../models';
import {config} from '../models';

export function AddProcess(arg1:Record<string, any>):Promise<void>;

export function ClearExceptions():Promise<void>;

export function ClearLogs():Promise<void>;

export function ClearQueryStatistics():Promise<void>;

export function ConnectDatabase(arg1:Record<string, any>):Promise<void>;

export function DeleteSavedConnection(arg1:string):Promise<void>;

export function DeleteSavedQuery(arg1:string):Promise<void>;

export function DisconnectDatabase():Promise<void>;

export function ExecuteDatabaseQuery(arg1:string,arg2:number):Promise<database.QueryResult>;

export function ExplainDatabaseQuery(arg1:string):Promise<database.ExplainResult>;

export function GetDatabaseHealth():Promise<database.DatabaseHealth>;

export function GetDatabaseStatus():Promise<database.DatabaseStatus>;

export function GetDatabaseTables():Promise<Array<database.TableInfo>>;

export function GetExceptions():Promise<Array<exceptions.Exception>>;

export function GetLogs(arg1:Record<string, any>):Promise<Array<main.LogEntry>>;

export function GetMetrics():Promise<metrics.Metrics>;

export function GetProcess(arg1:string):Promise<main.ProcessInfo>;

export function GetProcesses():Promise<Array<main.ProcessInfo>>;

export function GetProjectInfo():Promise<Record<string, any>>;

export function GetQueryStatistics():Promise<Array<database.QueryStatistic>>;

export function GetSavedConnections():Promise<Array<config.DatabaseConnection>>;

export function GetSavedQueries():Promise<Array<database.SavedQuery>>;

export function GetTableColumns(arg1:string):Promise<Array<database.ColumnInfo>>;

export function GetWorkerPoolStats():Promise<Record<string, any>>;

export function IgnoreException(arg1:string):Promise<void>;

export function IsRailsConsoleRunning():Promise<boolean>;

export function RemoveProcess(arg1:string):Promise<void>;

export function ResetMetrics():Promise<void>;

export function ResizePTY(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizeRailsConsole(arg1:number,arg2:number):Promise<void>;

export function ResolveException(arg1:string):Promise<void>;

export function RestartProcess(arg1:string):Promise<void>;

export function SaveDatabaseConnection(arg1:Record<string, any>):Promise<void>;

export function SaveDatabaseQuery(arg1:string,arg2:string):Promise<database.SavedQuery>;

export function SelectProjectDirectory():Promise<string>;

export function SetProjectDirectory(arg1:string):Promise<void>;

export function StartAllProcesses():Promise<void>;

export function StartProcess(arg1:string):Promise<void>;

export function StartRailsConsole():Promise<void>;

export function StopAllProcesses():Promise<void>;

export function StopProcess(arg1:string):Promise<void>;

export function StopRailsConsole():Promise<void>;

export function WriteToPTY(arg1:string,arg2:string):Promise<void>;

export function WriteToRailsConsole(arg1:string):Promise<void>;
