// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProcess(arg1) {
  return window['go']['main']['App']['AddProcess'](arg1);
}

export function ClearExceptions() {
  return window['go']['main']['App']['ClearExceptions']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearQueryStatistics() {
  return window['go']['main']['App']['ClearQueryStatistics']();
}

export function ConnectDatabase(arg1) {
  return window['go']['main']['App']['ConnectDatabase'](arg1);
}

export function DeleteSavedConnection(arg1) {
  return window['go']['main']['App']['DeleteSavedConnection'](arg1);
}

export function DeleteSavedQuery(arg1) {
  return window['go']['main']['App']['DeleteSavedQuery'](arg1);
}

export function DisconnectDatabase() {
  return window['go']['main']['App']['DisconnectDatabase']();
}

export function ExecuteDatabaseQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteDatabaseQuery'](arg1, arg2);
}

export function ExplainDatabaseQuery(arg1) {
  return window['go']['main']['App']['ExplainDatabaseQuery'](arg1);
}

export function GetDatabaseHealth() {
  return window['go']['main']['App']['GetDatabaseHealth']();
}

export function GetDatabaseStatus() {
  return window['go']['main']['App']['GetDatabaseStatus']();
}

export function GetDatabaseTables() {
  return window['go']['main']['App']['GetDatabaseTables']();
}

export function GetExceptions() {
  return window['go']['main']['App']['GetExceptions']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetProcess(arg1) {
  return window['go']['main']['App']['GetProcess'](arg1);
}

export function GetProcesses() {
  return window['go']['main']['App']['GetProcesses']();
}

export function GetProjectInfo() {
  return window['go']['main']['App']['GetProjectInfo']();
}

export function GetQueryStatistics() {
  return window['go']['main']['App']['GetQueryStatistics']();
}

export function GetSavedConnections() {
  return window['go']['main']['App']['GetSavedConnections']();
}

export function GetSavedQueries() {
  return window['go']['main']['App']['GetSavedQueries']();
}

export function GetTableColumns(arg1) {
  return window['go']['main']['App']['GetTableColumns'](arg1);
}

export function GetWorkerPoolStats() {
  return window['go']['main']['App']['GetWorkerPoolStats']();
}

export function IgnoreException(arg1) {
  return window['go']['main']['App']['IgnoreException'](arg1);
}

export function IsRailsConsoleRunning() {
  return window['go']['main']['App']['IsRailsConsoleRunning']();
}

export function RemoveProcess(arg1) {
  return window['go']['main']['App']['RemoveProcess'](arg1);
}

export function ResetMetrics() {
  return window['go']['main']['App']['ResetMetrics']();
}

export function ResizePTY(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizePTY'](arg1, arg2, arg3);
}

export function ResizeRailsConsole(arg1, arg2) {
  return window['go']['main']['App']['ResizeRailsConsole'](arg1, arg2);
}

export function ResolveException(arg1) {
  return window['go']['main']['App']['ResolveException'](arg1);
}

export function RestartProcess(arg1) {
  return window['go']['main']['App']['RestartProcess'](arg1);
}

export function SaveDatabaseConnection(arg1) {
  return window['go']['main']['App']['SaveDatabaseConnection'](arg1);
}

export function SaveDatabaseQuery(arg1, arg2) {
  return window['go']['main']['App']['SaveDatabaseQuery'](arg1, arg2);
}

export function SelectProjectDirectory() {
  return window['go']['main']['App']['SelectProjectDirectory']();
}

export function SetProjectDirectory(arg1) {
  return window['go']['main']['App']['SetProjectDirectory'](arg1);
}

export function StartAllProcesses() {
  return window['go']['main']['App']['StartAllProcesses']();
}

export function StartProcess(arg1) {
  return window['go']['main']['App']['StartProcess'](arg1);
}

export function StartRailsConsole() {
  return window['go']['main']['App']['StartRailsConsole']();
}

export function StopAllProcesses() {
  return window['go']['main']['App']['StopAllProcesses']();
}

export function StopProcess(arg1) {
  return window['go']['main']['App']['StopProcess'](arg1);
}

export function StopRailsConsole() {
  return window['go']['main']['App']['StopRailsConsole']();
}

export function WriteToPTY(arg1, arg2) {
  return window['go']['main']['App']['WriteToPTY'](arg1, arg2);
}

export function WriteToRailsConsole(arg1) {
  return window['go']['main']['App']['WriteToRailsConsole'](arg1);
}
