// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProcess(arg1) {
  return window['go']['main']['App']['AddProcess'](arg1);
}

export function CheckoutGitBranch(arg1) {
  return window['go']['main']['App']['CheckoutGitBranch'](arg1);
}

export function ClearExceptions() {
  return window['go']['main']['App']['ClearExceptions']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearQueryStatistics() {
  return window['go']['main']['App']['ClearQueryStatistics']();
}

export function CommitChanges(arg1) {
  return window['go']['main']['App']['CommitChanges'](arg1);
}

export function CompareQueryPlans(arg1, arg2) {
  return window['go']['main']['App']['CompareQueryPlans'](arg1, arg2);
}

export function ConfirmAndExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfirmAndExecuteQuery'](arg1, arg2, arg3);
}

export function ConnectDatabase(arg1) {
  return window['go']['main']['App']['ConnectDatabase'](arg1);
}

export function ConnectSSH(arg1) {
  return window['go']['main']['App']['ConnectSSH'](arg1);
}

export function CreateGitBranch(arg1, arg2) {
  return window['go']['main']['App']['CreateGitBranch'](arg1, arg2);
}

export function CreateSSHTunnel(arg1, arg2) {
  return window['go']['main']['App']['CreateSSHTunnel'](arg1, arg2);
}

export function DeleteGitBranch(arg1, arg2) {
  return window['go']['main']['App']['DeleteGitBranch'](arg1, arg2);
}

export function DeleteSSHServer(arg1) {
  return window['go']['main']['App']['DeleteSSHServer'](arg1);
}

export function DeleteSavedConnection(arg1) {
  return window['go']['main']['App']['DeleteSavedConnection'](arg1);
}

export function DeleteSavedQuery(arg1) {
  return window['go']['main']['App']['DeleteSavedQuery'](arg1);
}

export function DiscardChanges(arg1) {
  return window['go']['main']['App']['DiscardChanges'](arg1);
}

export function DisconnectDatabase() {
  return window['go']['main']['App']['DisconnectDatabase']();
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function ExecuteDatabaseQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecuteDatabaseQuery'](arg1, arg2);
}

export function ExplainDatabaseQuery(arg1) {
  return window['go']['main']['App']['ExplainDatabaseQuery'](arg1);
}

export function ExportSSHSession(arg1, arg2) {
  return window['go']['main']['App']['ExportSSHSession'](arg1, arg2);
}

export function GetAvailablePlugins() {
  return window['go']['main']['App']['GetAvailablePlugins']();
}

export function GetConflictFile(arg1) {
  return window['go']['main']['App']['GetConflictFile'](arg1);
}

export function GetDatabaseHealth() {
  return window['go']['main']['App']['GetDatabaseHealth']();
}

export function GetDatabaseStatus() {
  return window['go']['main']['App']['GetDatabaseStatus']();
}

export function GetDatabaseTables() {
  return window['go']['main']['App']['GetDatabaseTables']();
}

export function GetDebugConfiguration() {
  return window['go']['main']['App']['GetDebugConfiguration']();
}

export function GetExceptions() {
  return window['go']['main']['App']['GetExceptions']();
}

export function GetFrameworkInfo() {
  return window['go']['main']['App']['GetFrameworkInfo']();
}

export function GetGitBlame(arg1) {
  return window['go']['main']['App']['GetGitBlame'](arg1);
}

export function GetGitBranches() {
  return window['go']['main']['App']['GetGitBranches']();
}

export function GetGitDiff(arg1) {
  return window['go']['main']['App']['GetGitDiff'](arg1);
}

export function GetGitLog(arg1) {
  return window['go']['main']['App']['GetGitLog'](arg1);
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetN1Warnings() {
  return window['go']['main']['App']['GetN1Warnings']();
}

export function GetProcess(arg1) {
  return window['go']['main']['App']['GetProcess'](arg1);
}

export function GetProcesses() {
  return window['go']['main']['App']['GetProcesses']();
}

export function GetProjectInfo() {
  return window['go']['main']['App']['GetProjectInfo']();
}

export function GetQueryDistribution() {
  return window['go']['main']['App']['GetQueryDistribution']();
}

export function GetQueryStatistics() {
  return window['go']['main']['App']['GetQueryStatistics']();
}

export function GetRequestQueryGroups(arg1) {
  return window['go']['main']['App']['GetRequestQueryGroups'](arg1);
}

export function GetSSHServers() {
  return window['go']['main']['App']['GetSSHServers']();
}

export function GetSSHSessions() {
  return window['go']['main']['App']['GetSSHSessions']();
}

export function GetSavedConnections() {
  return window['go']['main']['App']['GetSavedConnections']();
}

export function GetSavedQueries() {
  return window['go']['main']['App']['GetSavedQueries']();
}

export function GetSmartRecommendations() {
  return window['go']['main']['App']['GetSmartRecommendations']();
}

export function GetTableColumns(arg1) {
  return window['go']['main']['App']['GetTableColumns'](arg1);
}

export function GetTestRunner() {
  return window['go']['main']['App']['GetTestRunner']();
}

export function GetWorkerPoolStats() {
  return window['go']['main']['App']['GetWorkerPoolStats']();
}

export function IgnoreException(arg1) {
  return window['go']['main']['App']['IgnoreException'](arg1);
}

export function IgnoreQueryPattern(arg1) {
  return window['go']['main']['App']['IgnoreQueryPattern'](arg1);
}

export function IsGitRepository() {
  return window['go']['main']['App']['IsGitRepository']();
}

export function IsRailsConsoleRunning() {
  return window['go']['main']['App']['IsRailsConsoleRunning']();
}

export function ParseLogWithPlugin(arg1) {
  return window['go']['main']['App']['ParseLogWithPlugin'](arg1);
}

export function RemoveProcess(arg1) {
  return window['go']['main']['App']['RemoveProcess'](arg1);
}

export function ResetMetrics() {
  return window['go']['main']['App']['ResetMetrics']();
}

export function ResizePTY(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizePTY'](arg1, arg2, arg3);
}

export function ResizeRailsConsole(arg1, arg2) {
  return window['go']['main']['App']['ResizeRailsConsole'](arg1, arg2);
}

export function ResizeSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSSH'](arg1, arg2, arg3);
}

export function ResolveConflict(arg1, arg2) {
  return window['go']['main']['App']['ResolveConflict'](arg1, arg2);
}

export function ResolveException(arg1) {
  return window['go']['main']['App']['ResolveException'](arg1);
}

export function RestartProcess(arg1) {
  return window['go']['main']['App']['RestartProcess'](arg1);
}

export function RevertFile(arg1) {
  return window['go']['main']['App']['RevertFile'](arg1);
}

export function RevertFileToCommit(arg1, arg2) {
  return window['go']['main']['App']['RevertFileToCommit'](arg1, arg2);
}

export function SaveDatabaseConnection(arg1) {
  return window['go']['main']['App']['SaveDatabaseConnection'](arg1);
}

export function SaveDatabaseQuery(arg1, arg2) {
  return window['go']['main']['App']['SaveDatabaseQuery'](arg1, arg2);
}

export function SaveSSHServer(arg1) {
  return window['go']['main']['App']['SaveSSHServer'](arg1);
}

export function SelectProjectDirectory() {
  return window['go']['main']['App']['SelectProjectDirectory']();
}

export function SetProjectDirectory(arg1) {
  return window['go']['main']['App']['SetProjectDirectory'](arg1);
}

export function StageFiles(arg1) {
  return window['go']['main']['App']['StageFiles'](arg1);
}

export function StartAllProcesses() {
  return window['go']['main']['App']['StartAllProcesses']();
}

export function StartProcess(arg1) {
  return window['go']['main']['App']['StartProcess'](arg1);
}

export function StartRailsConsole() {
  return window['go']['main']['App']['StartRailsConsole']();
}

export function StopAllProcesses() {
  return window['go']['main']['App']['StopAllProcesses']();
}

export function StopProcess(arg1) {
  return window['go']['main']['App']['StopProcess'](arg1);
}

export function StopRailsConsole() {
  return window['go']['main']['App']['StopRailsConsole']();
}

export function UnstageFiles(arg1) {
  return window['go']['main']['App']['UnstageFiles'](arg1);
}

export function WriteSSH(arg1, arg2) {
  return window['go']['main']['App']['WriteSSH'](arg1, arg2);
}

export function WriteToPTY(arg1, arg2) {
  return window['go']['main']['App']['WriteToPTY'](arg1, arg2);
}

export function WriteToRailsConsole(arg1) {
  return window['go']['main']['App']['WriteToRailsConsole'](arg1);
}
